### ISSUE TITLE
Reporting IPs by Users

### ISSUE THREAD

**Issue by TotenKnopf** [GHCDiscord/IP-Database#10]
1. Function is not working at all (no coloring is applied)
see https://github.com/GHCDiscord/IP-Database/blob/master/classes/ip.php#L97
this is not working for me with the removed "$" and count set to 1.

2. Admin / Contributor deletion of an IP does not remove the report itself -> database trash
test locally with this: 
```SQL
SELECT * FROM `IPUserReport` left join `HackersIP` on `IPUserReport`.`IPID` = `HackersIP`.`ID` Order by `Name`
```

**Comment by Grumbledore667** [comment]
Class = "danger"; for the coloring

For the snd part I did not alter anything at those functions. Will need to look into that

**Comment by atalanthus** [comment]
`if($row["CountIPRepo"] >= 5) {
               $class = "danger";
 }`
oder?

**Comment by TotenKnopf** [comment]
ata: danke. ist schon gepushed und funktiniert :)

todo: (notiz an mich / dade):
"Index.php ---> menu.php im navbar.php ändern
Login.php --> $accountexpired auskommentieren oder löschen"

Problem 2 müssen wir nochmal separat ran.

**Comment by atalanthus** [comment]
Was genau bedeutet: Index.php ---> menu.php im navbar.php ändern

**Comment by TotenKnopf** [comment]
issue solved. 
opening #2 in a new issue
