### ISSUE TITLE
user reports trashing database

### ISSUE THREAD

**Issue by TotenKnopf** [GHCDiscord/IP-Database#13]
Admin / Contributor deletion of an IP does not remove the report itself -> database trash
test locally with this: 
```SQL
SELECT * FROM `IPUserReport` left join `HackersIP` on `IPUserReport`.`IPID` = `HackersIP`.`ID` Order by `Name`
```

**Comment by Grumbledore667** [comment]
http://stackoverflow.com/questions/8333302/mysql-foreign-key-on-delete

Need to change the foreign key to on delete Cascade and on update cascade

**Comment by TotenKnopf** [comment]
from Dade: 
# Primärschlüssel für Tabelle IPUserReport
- Bitte hier nachträglich den Primärschlüssel RID mit Auto increment hinzufügen danke.
- Dasselbe bitte bei IPUserFav dort FID und in der Tabelle UserID und IPID als fremdschlüssel setzten mit Cascade auf delete und Update. Sie die issue mit dem trash

**Comment by TotenKnopf** [comment]
Added new Primary key: `IPUserReport` + AI.
```SQL
ALTER TABLE `IPUserReport` ADD `RID` INT(11) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`RID`);
```

**Comment by TotenKnopf** [comment]
Added new primary key: `IPUserFav`.`FID` + AI
```SQL
ALTER TABLE `IPUserFav` ADD `FID` INT(11) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`FID`);
```

**Comment by TotenKnopf** [comment]
```SQL
ALTER TABLE `IPUserFav` 
ADD FOREIGN KEY (`UserID`) REFERENCES `Users` (`ID`)
ON UPDATE CASCADE 
ON DELETE CASCADE;

ALTER TABLE `IPUserFav` 
ADD FOREIGN KEY (`IPID`) REFERENCES `HackersIP` (`ID`)
ON UPDATE CASCADE 
ON DELETE CASCADE;

ALTER TABLE `IPUserReport`
ADD FOREIGN KEY (`UserID`) REFERENCES `Users` (`ID`)
ON UPDATE CASCADE 
ON DELETE CASCADE;

ALTER TABLE `IPUserReport`
ADD FOREIGN KEY (`IPID`) REFERENCES `HackersIP` (`ID`)
ON UPDATE CASCADE 
ON DELETE CASCADE;
```
