### ISSUE TITLE
added_by NULL

### ISSUE THREAD

**Issue by TotenKnopf** [GHCDiscord/IP-Database#15]
"Kann mal jemand in der DB schauen was mit der IP 180.201.171.75 los ist? Beim Hinzufügen durch Bot oder auf der Seite heißt es es gäbe sie schon, beim suchen finde ich sie aber nicht. Ausgeblendet kann sie aber auch nicht sein, da kein passender Nutzername existiert"
"wieder der NULL Fehler"
"Ich habe die IP nämlich hinzugefügt, nachdem die Seite länger im Leerlauf war (-> ich wurde automatisch ausgeloggt). Danach habe ich auf AddIP gedrückt und wurde auf die Anmeldeseite weitergeleitet. Die IP ist aber jetzt trotzdem in der DB"

**Comment by Grumbledore667** [comment]
In einem meiner commits ein loggedin Check hinzugefügt. Das sollte das NULL Problem erstmal beseitigen. Alternativ die ID des admins als Default setzen.

**Comment by TotenKnopf** [comment]
bei den aktuellen NULL werten updated auf 37 = admin gesetzt
danke für den fix.
