### ISSUE TITLE
Primärschlüssel für Tabelle IPUserReport

### ISSUE THREAD

**Issue by Grumbledore667** [GHCDiscord/IP-Database#17]
Bitte hier nachträglich den Primärschlüssel RID mit Auto increment hinzufügen danke.

**Comment by Grumbledore667** [comment]
Dasselbe bitte bei IPUserFav dort FID und in der Tabelle UserID und IPID als fremdschlüssel setzten mit Cascade auf delete und Update. Sie die issue mit dem trash

**Comment by TotenKnopf** [comment]
see https://github.com/GHCDiscord/IP-Database/issues/13
closed here
